apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: flask-deployment
  template:
    metadata:
      labels:
        app: flask-deployment
    spec:
      containers:
      - name: flask-app
        image: europe-west1-docker.pkg.dev/matrix-devops/matrix-devops/flask-app:latest
        resources:
          requests:
            cpu: "100m"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP