apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  selector:
  matchLabels:
    app: flask-deployment
  template:
  metadata:
    labels:
      app: flask-deployment
  spec:
    containers:
    - name: flask-app
      image: europe-west1-docker.pkg.dev/matrix-devops/matrix-devops/flask-app:latest
      ports:
      - name: http
        containerPort: 80
        protocol: TCP